# Generated by Django 3.2.4 on 2021-07-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       # ('users', '0002_auto_20210707_1339'),
       # ('users', '0003_rename_enterprise_id_user_login_log_brand_id'),
    ]

    operations = [
    ]
