# Generated by Django 3.2.4 on 2021-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_login_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_logo',
            field=models.ImageField(blank=True, null=True, upload_to='http://52.66.228.107:8080/media/users/logo'),
        ),
    ]
