# Generated by Django 3.2.4 on 2021-07-16 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobusers', '0001_initial'),
        ('postcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('poll', 'Poll'), ('quiz', 'Quiz')], max_length=30)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_file/')),
                ('post_file', models.FileField(blank=True, null=True, upload_to='post_file/')),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('url', 'URL')], max_length=30, null=True)),
                ('taggedusers', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('is_entity', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('approve_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Blocked')], default=0)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reactions', models.JSONField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('Chinese', 'Chinese'), ('Russian', 'Russian')], max_length=30, null=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_by', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('post_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='postcategory.postcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers')),
            ],
            options={
                'db_table': 'amrc_posts',
            },
        ),
        migrations.CreateModel(
            name='PostsReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_track_status', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.posts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers')),
            ],
            options={
                'db_table': 'amrc_post_reactions',
            },
        ),
        migrations.CreateModel(
            name='PostActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(blank=True, max_length=255, null=True)),
                ('option_val', models.TextField(blank=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.posts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers')),
            ],
            options={
                'db_table': 'amrc_post_activities',
            },
        ),
    ]
