# Generated by Django 3.2.4 on 2021-08-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_posts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
