# Generated by Django 3.2.4 on 2021-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_posts_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='heart_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='shock_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='smile_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
