# Generated by Django 3.2.4 on 2021-08-13 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0002_alter_jobusers_userprofileimage'),
        ('post', '0005_auto_20210811_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.posts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers')),
            ],
            options={
                'db_table': 'amrc_post_comments',
            },
        ),
    ]
