# Generated by Django 3.2.4 on 2021-08-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
    ]
