# Generated by Django 3.2.4 on 2021-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210823_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
