# Generated by Django 3.2.4 on 2021-08-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_posts_post_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_language',
            field=models.IntegerField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('Chinese', 'Chinese'), ('Russian', 'Russian')], default=0, null=True),
        ),
    ]
