# Generated by Django 3.2.4 on 2021-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_posts_post_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_language',
            field=models.IntegerField(choices=[(0, 'English'), (1, 'Arabic')], default=0, null=True),
        ),
    ]
