# Generated by Django 3.2.4 on 2021-09-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210830_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
