# Generated by Django 3.2.4 on 2021-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_posts_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_file',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='posts',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
    ]
