# Generated by Django 3.2.4 on 2021-09-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_posts_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_file',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.JSONField(default=list),
        ),
    ]
