# Generated by Django 3.2.4 on 2021-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20210917_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('poll', 'Poll'), ('quiz', 'Quiz'), ('birthday', 'Birthday')], max_length=30),
        ),
        migrations.AlterField(
            model_name='posts',
            name='reactions',
            field=models.JSONField(default=list),
        ),
    ]
