# Generated by Django 3.2.4 on 2021-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210816_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='isimage',
            field=models.BooleanField(default=False),
        ),
    ]
