# Generated by Django 3.2.4 on 2021-08-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0002_alter_jobusers_userprofileimage'),
        ('quiz', '0003_quizquestions_isimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('timetaken', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_by', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.quizes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers')),
            ],
            options={
                'db_table': 'amrc_quiz_result',
            },
        ),
    ]
