# Generated by Django 3.2.4 on 2021-08-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0002_alter_jobusers_userprofileimage'),
        ('quiz', '0004_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers'),
        ),
    ]
