# Generated by Django 3.2.4 on 2021-08-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizes',
            name='user',
        ),
    ]
