# Generated by Django 3.2.4 on 2021-08-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210819_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='user',
            new_name='job_user',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='updated_by',
        ),
    ]
