# Generated by Django 3.2.4 on 2021-08-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210819_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='question_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.quizquestions'),
        ),
    ]
