# Generated by Django 3.2.4 on 2021-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210819_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
