# Generated by Django 3.2.4 on 2021-08-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='answer_given',
            field=models.TextField(blank=True, null=True),
        ),
    ]
