# Generated by Django 3.2.4 on 2021-08-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quizresult_answer_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
