# Generated by Django 3.2.4 on 2021-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quizresult_quiz_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
