# Generated by Django 3.2.4 on 2021-08-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_quizresult_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
    ]
