# Generated by Django 3.2.4 on 2021-08-31 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0007_jobusers_brand_id'),
        ('quiz', '0014_auto_20210826_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_questions', models.IntegerField(default=0)),
                ('attempted_questions', models.IntegerField(default=0)),
                ('totaltimetaken', models.FloatField(default=0.0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.quizes')),
            ],
            options={
                'db_table': 'amrc_quiz_final_result',
            },
        ),
    ]
