# Generated by Django 3.2.4 on 2021-08-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quizfinalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
