# Generated by Django 3.2.4 on 2021-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_quizresult_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='result',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='answer_given',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
