# Generated by Django 3.2.4 on 2021-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20210831_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfinalresult',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
