# Generated by Django 3.2.4 on 2021-09-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushNotification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
