# Generated by Django 3.2.4 on 2021-07-16 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rewards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarOfTheMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('award_lebel', models.IntegerField(choices=[(1, 'Award-1'), (2, 'Award-2'), (3, 'Award-3')])),
                ('selected_date', models.DateField(blank=True, null=True, validators=[rewards.models.validate_date])),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_by', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers')),
            ],
            options={
                'db_table': 'amrc_start_of_the_month',
            },
        ),
    ]
