# Generated by Django 3.2.4 on 2021-08-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='name',
            new_name='title',
        ),
    ]
