# Generated by Django 3.2.4 on 2021-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_alter_points_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
