# Generated by Django 3.2.4 on 2021-08-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_points_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='starofthemonth',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
    ]
