# Generated by Django 3.2.4 on 2021-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_auto_20210930_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starofthemonth',
            name='award_lebel',
        ),
        migrations.RemoveField(
            model_name='starofthemonth',
            name='selected_date',
        ),
        migrations.AddField(
            model_name='starofthemonth',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starofthemonth',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
    ]
