# Generated by Django 3.2.4 on 2021-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
    ]
