# Generated by Django 3.2.4 on 2021-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0002_alter_jobusers_userprofileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobusers',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
