# Generated by Django 3.2.4 on 2021-08-25 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0003_jobusers_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_User_Points_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField(default=0)),
                ('point_slug', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('point_desc', models.TextField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobusers.jobusers')),
            ],
            options={
                'db_table': 'amrc_job_user_points_log',
            },
        ),
    ]
