# Generated by Django 3.2.4 on 2021-08-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0005_auto_20210825_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobusers',
            name='language',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
