# Generated by Django 3.2.4 on 2021-09-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0007_jobusers_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobusers',
            name='points',
        ),
        migrations.AlterField(
            model_name='jobusers',
            name='reg_id',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobusers',
            name='user_point',
            field=models.BigIntegerField(default=0, help_text='User total point'),
        ),
    ]
