# Generated by Django 3.2.4 on 2021-09-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0008_auto_20210901_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_user_points_log',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='job_user_points_log',
            name='point_action',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
