# Generated by Django 3.2.4 on 2021-09-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0009_auto_20210906_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobusers',
            old_name='reg_id',
            new_name='device_id',
        ),
        migrations.AddField(
            model_name='jobusers',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
